// ignore_for_file: annotate_overrides, camel_case_types, comment_references, constant_identifier_names, curly_braces_in_flow_control_structures, deprecated_member_use, deprecated_member_use_from_same_package, directives_ordering, library_prefixes, non_constant_identifier_names, prefer_final_fields, return_of_invalid_type, unnecessary_const, unnecessary_import, unnecessary_this, unused_import, unused_shown_name, unintended_html_in_doc_comment
// This is a generated file - do not edit.
//
// Generated from auxiliary/tss/tss_message.proto.

// @dart = 3.3

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names
// ignore_for_file: curly_braces_in_flow_control_structures
// ignore_for_file: deprecated_member_use_from_same_package, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_relative_imports

import 'dart:core' as $core;

import 'package:fixnum/fixnum.dart' as $fixnum;
import 'package:protobuf/protobuf.dart' as $pb;

export 'package:protobuf/protobuf.dart' show GeneratedMessageGenericExtensions;

/// * A transaction body to to send a Threshold Signature Scheme (TSS)
///  Message.<br/>
///  This is a wrapper around several different TSS message types that a node
///  might communicate with other nodes in the network.
///
///  - A `TssMessageTransactionBody` MUST identify the hash of the roster
///    containing the node generating this TssMessage
///  - A `TssMessageTransactionBody` MUST identify the hash of the roster that
///    the TSS messages is for
///  - A `TssMessageTransactionBody` SHALL contain the specificc TssMessage data
///    that has been generated by the node for the share_index.
class TssMessageTransactionBody extends $pb.GeneratedMessage {
  factory TssMessageTransactionBody({
    $core.List<$core.int>? sourceRosterHash,
    $core.List<$core.int>? targetRosterHash,
    $fixnum.Int64? shareIndex,
    $core.List<$core.int>? tssMessage,
  }) {
    final result = create();
    if (sourceRosterHash != null) result.sourceRosterHash = sourceRosterHash;
    if (targetRosterHash != null) result.targetRosterHash = targetRosterHash;
    if (shareIndex != null) result.shareIndex = shareIndex;
    if (tssMessage != null) result.tssMessage = tssMessage;
    return result;
  }

  TssMessageTransactionBody._();

  factory TssMessageTransactionBody.fromBuffer($core.List<$core.int> data,
          [$pb.ExtensionRegistry registry = $pb.ExtensionRegistry.EMPTY]) =>
      create()..mergeFromBuffer(data, registry);
  factory TssMessageTransactionBody.fromJson($core.String json,
          [$pb.ExtensionRegistry registry = $pb.ExtensionRegistry.EMPTY]) =>
      create()..mergeFromJson(json, registry);

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(
      _omitMessageNames ? '' : 'TssMessageTransactionBody',
      package: const $pb.PackageName(
          _omitMessageNames ? '' : 'com.hedera.hapi.services.auxiliary.tss'),
      createEmptyInstance: create)
    ..a<$core.List<$core.int>>(
        1, _omitFieldNames ? '' : 'sourceRosterHash', $pb.PbFieldType.OY)
    ..a<$core.List<$core.int>>(
        2, _omitFieldNames ? '' : 'targetRosterHash', $pb.PbFieldType.OY)
    ..a<$fixnum.Int64>(
        3, _omitFieldNames ? '' : 'shareIndex', $pb.PbFieldType.OU6,
        defaultOrMaker: $fixnum.Int64.ZERO)
    ..a<$core.List<$core.int>>(
        4, _omitFieldNames ? '' : 'tssMessage', $pb.PbFieldType.OY)
    ..hasRequiredFields = false;

  @$core.Deprecated('See https://github.com/google/protobuf.dart/issues/998.')
  TssMessageTransactionBody clone() => deepCopy();
  @$core.Deprecated('See https://github.com/google/protobuf.dart/issues/998.')
  TssMessageTransactionBody copyWith(
          void Function(TssMessageTransactionBody) updates) =>
      super.copyWith((message) => updates(message as TssMessageTransactionBody))
          as TssMessageTransactionBody;

  @$core.override
  $pb.BuilderInfo get info_ => _i;

  @$core.pragma('dart2js:noInline')
  static TssMessageTransactionBody create() => TssMessageTransactionBody._();
  @$core.override
  TssMessageTransactionBody createEmptyInstance() => create();
  @$core.pragma('dart2js:noInline')
  static TssMessageTransactionBody getDefault() => _defaultInstance ??=
      $pb.GeneratedMessage.$_defaultFor<TssMessageTransactionBody>(create);
  static TssMessageTransactionBody? _defaultInstance;

  /// *
  ///  A hash of the roster containing the node generating the TssMessage.<br/>
  ///  This hash uniquely identifies the source roster, which will include
  ///  an entry for the node generating this TssMessage.
  ///  <p>
  ///  This value MUST be set.<br/>
  ///  This value MUST NOT be empty.<br/>
  ///  This value MUST contain a valid hash.
  @$pb.TagNumber(1)
  $core.List<$core.int> get sourceRosterHash => $_getN(0);
  @$pb.TagNumber(1)
  set sourceRosterHash($core.List<$core.int> value) => $_setBytes(0, value);
  @$pb.TagNumber(1)
  $core.bool hasSourceRosterHash() => $_has(0);
  @$pb.TagNumber(1)
  void clearSourceRosterHash() => $_clearField(1);

  /// *
  ///  A hash of the roster that the TssMessage is for.
  ///  <p>
  ///  This value MUST be set.<br/>
  ///  This value MUST NOT be empty.<br/>
  ///  This value MUST contain a valid hash.
  @$pb.TagNumber(2)
  $core.List<$core.int> get targetRosterHash => $_getN(1);
  @$pb.TagNumber(2)
  set targetRosterHash($core.List<$core.int> value) => $_setBytes(1, value);
  @$pb.TagNumber(2)
  $core.bool hasTargetRosterHash() => $_has(1);
  @$pb.TagNumber(2)
  void clearTargetRosterHash() => $_clearField(2);

  /// *
  ///  An index to order shares.
  ///  <p>
  ///  A share index SHALL establish a global ordering of shares across all
  ///  shares in the network.<br/>
  ///  A share index MUST correspond to the index of the public share in the list
  ///  returned from the TSS library when the share was created for the source
  ///  roster.
  @$pb.TagNumber(3)
  $fixnum.Int64 get shareIndex => $_getI64(2);
  @$pb.TagNumber(3)
  set shareIndex($fixnum.Int64 value) => $_setInt64(2, value);
  @$pb.TagNumber(3)
  $core.bool hasShareIndex() => $_has(2);
  @$pb.TagNumber(3)
  void clearShareIndex() => $_clearField(3);

  /// *
  ///  A byte array.
  ///  <p>
  ///  This field SHALL contain the TssMessage data generated by the node
  ///  for the specified `share_index`.
  @$pb.TagNumber(4)
  $core.List<$core.int> get tssMessage => $_getN(3);
  @$pb.TagNumber(4)
  set tssMessage($core.List<$core.int> value) => $_setBytes(3, value);
  @$pb.TagNumber(4)
  $core.bool hasTssMessage() => $_has(3);
  @$pb.TagNumber(4)
  void clearTssMessage() => $_clearField(4);
}

const $core.bool _omitFieldNames =
    $core.bool.fromEnvironment('protobuf.omit_field_names');
const $core.bool _omitMessageNames =
    $core.bool.fromEnvironment('protobuf.omit_message_names');
